// Generated by gencpp from file com_test/ADDsumResponse.msg
// DO NOT EDIT!


#ifndef COM_TEST_MESSAGE_ADDSUMRESPONSE_H
#define COM_TEST_MESSAGE_ADDSUMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com_test
{
template <class ContainerAllocator>
struct ADDsumResponse_
{
  typedef ADDsumResponse_<ContainerAllocator> Type;

  ADDsumResponse_()
    : sum(0)  {
    }
  ADDsumResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::com_test::ADDsumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com_test::ADDsumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ADDsumResponse_

typedef ::com_test::ADDsumResponse_<std::allocator<void> > ADDsumResponse;

typedef boost::shared_ptr< ::com_test::ADDsumResponse > ADDsumResponsePtr;
typedef boost::shared_ptr< ::com_test::ADDsumResponse const> ADDsumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com_test::ADDsumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com_test::ADDsumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com_test::ADDsumResponse_<ContainerAllocator1> & lhs, const ::com_test::ADDsumResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com_test::ADDsumResponse_<ContainerAllocator1> & lhs, const ::com_test::ADDsumResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com_test::ADDsumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com_test::ADDsumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com_test::ADDsumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com_test::ADDsumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com_test::ADDsumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com_test::ADDsumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com_test::ADDsumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::com_test::ADDsumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::com_test::ADDsumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com_test/ADDsumResponse";
  }

  static const char* value(const ::com_test::ADDsumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com_test::ADDsumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#服务器响应发送的数据server(服务端)\n"
"int32 sum\n"
;
  }

  static const char* value(const ::com_test::ADDsumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com_test::ADDsumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ADDsumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com_test::ADDsumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com_test::ADDsumResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM_TEST_MESSAGE_ADDSUMRESPONSE_H
