// Generated by gencpp from file com_test/ADDsumRequest.msg
// DO NOT EDIT!


#ifndef COM_TEST_MESSAGE_ADDSUMREQUEST_H
#define COM_TEST_MESSAGE_ADDSUMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com_test
{
template <class ContainerAllocator>
struct ADDsumRequest_
{
  typedef ADDsumRequest_<ContainerAllocator> Type;

  ADDsumRequest_()
    : num1(0)
    , num2(0)  {
    }
  ADDsumRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;

   typedef int32_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::com_test::ADDsumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com_test::ADDsumRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ADDsumRequest_

typedef ::com_test::ADDsumRequest_<std::allocator<void> > ADDsumRequest;

typedef boost::shared_ptr< ::com_test::ADDsumRequest > ADDsumRequestPtr;
typedef boost::shared_ptr< ::com_test::ADDsumRequest const> ADDsumRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com_test::ADDsumRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com_test::ADDsumRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com_test::ADDsumRequest_<ContainerAllocator1> & lhs, const ::com_test::ADDsumRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com_test::ADDsumRequest_<ContainerAllocator1> & lhs, const ::com_test::ADDsumRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com_test::ADDsumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com_test::ADDsumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com_test::ADDsumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com_test::ADDsumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com_test::ADDsumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com_test::ADDsumRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com_test::ADDsumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c68f3979e1a90aac7d1c75a1096d1e60";
  }

  static const char* value(const ::com_test::ADDsumRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc68f3979e1a90aacULL;
  static const uint64_t static_value2 = 0x7d1c75a1096d1e60ULL;
};

template<class ContainerAllocator>
struct DataType< ::com_test::ADDsumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com_test/ADDsumRequest";
  }

  static const char* value(const ::com_test::ADDsumRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com_test::ADDsumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#客户端请求的数据client(请求端)\n"
"int32 num1\n"
"int32 num2\n"
;
  }

  static const char* value(const ::com_test::ADDsumRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com_test::ADDsumRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ADDsumRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com_test::ADDsumRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com_test::ADDsumRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM_TEST_MESSAGE_ADDSUMREQUEST_H
