// Generated by gencpp from file com_test/ADDsum.msg
// DO NOT EDIT!


#ifndef COM_TEST_MESSAGE_ADDSUM_H
#define COM_TEST_MESSAGE_ADDSUM_H

#include <ros/service_traits.h>


#include <com_test/ADDsumRequest.h>
#include <com_test/ADDsumResponse.h>


namespace com_test
{

struct ADDsum
{

typedef ADDsumRequest Request;
typedef ADDsumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ADDsum
} // namespace com_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::com_test::ADDsum > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::com_test::ADDsum&) { return value(); }
};

template<>
struct DataType< ::com_test::ADDsum > {
  static const char* value()
  {
    return "com_test/ADDsum";
  }

  static const char* value(const ::com_test::ADDsum&) { return value(); }
};


// service_traits::MD5Sum< ::com_test::ADDsumRequest> should match
// service_traits::MD5Sum< ::com_test::ADDsum >
template<>
struct MD5Sum< ::com_test::ADDsumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::com_test::ADDsum >::value();
  }
  static const char* value(const ::com_test::ADDsumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::com_test::ADDsumRequest> should match
// service_traits::DataType< ::com_test::ADDsum >
template<>
struct DataType< ::com_test::ADDsumRequest>
{
  static const char* value()
  {
    return DataType< ::com_test::ADDsum >::value();
  }
  static const char* value(const ::com_test::ADDsumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::com_test::ADDsumResponse> should match
// service_traits::MD5Sum< ::com_test::ADDsum >
template<>
struct MD5Sum< ::com_test::ADDsumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::com_test::ADDsum >::value();
  }
  static const char* value(const ::com_test::ADDsumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::com_test::ADDsumResponse> should match
// service_traits::DataType< ::com_test::ADDsum >
template<>
struct DataType< ::com_test::ADDsumResponse>
{
  static const char* value()
  {
    return DataType< ::com_test::ADDsum >::value();
  }
  static const char* value(const ::com_test::ADDsumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COM_TEST_MESSAGE_ADDSUM_H
